### ISSUE TITLE
Unable to build the Config of ReRoCCManyGemminiConfig

### ISSUE THREAD

**Issue by Brandonyfyang** [ucb-bar/rerocc#9]
Nowadays, I'm trying to build the config of ReRoCCManyGemminiConfig

class ReRoCCManyGemminiConfig extends Config(
  new rerocc.WithReRoCC ++
  new gemmini.LeanGemminiConfig ++                              // rerocc tile3 is gemmini
  new gemmini.LeanGemminiConfig ++                              // rerocc tile2 is gemmini
  new gemmini.LeanGemminiConfig ++                              // rerocc tile1 is gemmini
  new gemmini.LeanGemminiConfig ++                              // rerocc tile0 is gemmini
  new freechips.rocketchip.rocket.WithNHugeCores(4) ++           // 4 rocket cores
  new chipyard.config.AbstractConfig)
However, an error happened:
`Caused by: java.lang.IllegalArgumentException: requirement failed: Memory region 'ctrl' at List(AddressSet(0x20000, 0xfff)) only supports TransferSizes[1, 8] Get, but must support TransferSizes[1, 64]`
With Chipyard: 1.13.0
With Gemmini: 0.7.2
With ReRoCC: The latest repo
With Verilator: 5.022

**Comment by jerryz123** [comment]
You want to be using the latest rerocc, you are missing a bug-fix on master
